### ISSUE TITLE
About datasets posted in directory `train -> display_datasets -> xmm_sim_display_selection` 

### ISSUE THREAD

**Issue by leungzzz** [SamSweere/xmm-superres-denoise#25]
When the params `log_images_every_n_epochs:5` and `display -> sim_display_name: xmm_sim_display_selection` be set, which kinds of dataset should be posted in directory `train -> display_datasets -> xmm_sim_display_selection` as described in `xmm_display_datamodule.py`? 

At this time i have scannd carefully all of four branches, neither of them mention it. I really just confused aboult it, sorry to bother again!

**Comment by bojobo** [comment]
Hi! No worries, I'm happy that you're interested in the project.

I was sure, that I have uploaded it... To make matters worse, I can't access the cluster where the data is at and I don't know why. I'll upload the images to huggingface as soon as I have access again. This could take some time.
 
@SamSweere Do you still have the `display_datasets`? Maybe you could share it.

Otherwise @leungzzz you can randomly choose images from the simulated dataset with the chosen exposure (see [here](https://github.com/SamSweere/xmm-superres-denoise/blob/31a98eb8dc7dc4d2e1540b973322993238be2208/res/baseline_config.yaml#L29)) and use those images. They are just there to have some visual feedback.

**Comment by SamSweere** [comment]
Hi @leungzzz and @bojobo,

It's great to see more people interested in working on ML in astronomy!

I have a local copy of all the data, which I can share. However, please note that the full dataset is approximately 200 GB. I've uploaded the display datasets and some smaller subsets that I used for development to Google Drive: [Google Drive Link](https://drive.google.com/drive/folders/18rsZGX5qDsd0LbIR9SSMqycEwgdmXcWe?usp=sharing).

Please note that I will likely remove this shared folder in a few weeks. If you need the full dataset, we can arrange a peer-to-peer transfer.

**Comment by leungzzz** [comment]
That's great to get your reply, @bojobo . At that time prepare to randomly choose images from the simulated dataset, then get that reply from you @SamSweere. Now i have got that `xmm_selection_datasets` from your temporarily shared [links](https://drive.google.com/drive/folders/18rsZGX5qDsd0LbIR9SSMqycEwgdmXcWe). Please let me know what preparations should I need to do if we build a peer-to-peer transfer, I just really have no much experience (not afraid to say).

It's really appreciate to get you two reply so timely.
